script:
  - java -version
  - ls -l
  - ls -l 0.9.60.0
  - unzip -q 0.9.60.0/cslang-cli-with-content.zip
  - echo "DO_TOKEN=${DO_TOKEN}"

  - >
    0.9.60.0/cslang-cli/bin/cslang.bat run
    --f /0.9.60.0/cloud-slang-content/content/io/cloudslang/cloud/digital_ocean/v2/examples/delete_zombie_droplets.sl
    --cp /0.9.60.0/cloud-slang-content/content/
    --i token=${DO_TOKEN}
