script:
  - java -version
  - unzip -q 0.9.60.0/cslang-cli-with-content.zip
  - ls -l 0.9.60.0
  - ls -l

  - chmod +x cslang-cli/bin/cslang.bat
  - >
    cslang-cli/bin/cslang run
    --f 0.9.60.0/cloud-slang-content/content/io/cloudslang/cloud/digital_ocean/v2/examples/delete_zombie_droplets.sl
    --cp 0.9.60.0/cloud-slang-content/content/
    --i token=${DO_TOKEN}
